### ISSUE TITLE
TimeShifter and TimeOffset tasks

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband-tasks#100]
Related but different in implementation:
- [X] Correct for clock offsets - this really is just a difference in start time. -> #104
- [X] Interpolate between samples -> #117
- [X] Shift & interpolate and apply corresponding phase shift -> #225

The most general case would correct for earth/pulsar motion during an observation (using a polyco or PINT), i.e., also stretch time and (Doppler) shift frequency.

Specific use cases:
- [X] Align two data streams to subsample precision for direct correlation. Implies offset of start_time + residual sample shift, plus taking into account associated phase changes.
- [X] Read out a giant pulse starting with its pulse peak, determined to subsample precision, falling on an integer sample. Easiest might seem to want to start on a specific time: implies new start_time + residual sample shift. Alternatively, call it `TimeSeek(ih, time)` which calculates the required sub-sample offset, initialites a `TimeShift` and then seeks to the requested `time`. This could also be a classmethod on `TimeShift`. EDIT: ended up just being easier as `Resample`
