### ISSUE TITLE
Tracking issue for releases 0.1 and 0.2

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband-tasks#182]
Plan:
- [x] Create changelog and expose it in documentation.
- [x] Tell how to get "scintillometry" in installation instructions.
- [x] Release 0.1 which has old requirements, including pypi/zenodo.
- [x] Update baseband docs to link to `baseband-tasks`.
- [x] See if it possible to create a nice `baseband.tasks` page. [EDIT] This actually is tricky: it seems hard to get sphinx to deal with the entry points. Need to deal with it in `baseband-tasks`?
- [x] Update requirement to baseband >= 4.0 (and whatever that implies).
- [x] Release baseband 4.0.1, to have "stable" docs point correctly to `baseband-tasks`.
- [x] Update documentation to import from `baseband.tasks`.
- [x] Release 0.2 that can work as plugin.
